export const FETCH_COMPANY_SEARCH_START =
  "FETCH_COMPANY_SEARCH_START"
export const FETCH_COMPANY_SEARCH_SUCCESS =
  "FETCH_COMPANY_SEARCH_SUCCESS"
export const FETCH_COMPANY_SEARCH_FAILED =
  "FETCH_COMPANY_SEARCH_FAILED"
  export const GET_ALL_COMPANY_LIST =
  "GET_ALL_COMPANY_LIST"

  export const GET_ALL_COMPANY_LIST_SUCCESS =
  "GET_ALL_COMPANY_LIST_SUCCESS"

  export const GET_ALL_COMPANY_LIST_FAIL =
  "GET_ALL_COMPANY_LIST_FAIL"


