export const FETCH_UPLOADING_PENDING_DOC_LIST_START =
  "FETCH_UPLOADING_PENDING_DOC_LIST_START"
export const FETCH_UPLOADING_PENDING_DOC_LIST_SUCCESS =
  "FETCH_UPLOADING_PENDING_DOC_LIST_SUCCESS"
export const FETCH_UPLOADING_PENDING_DOC_LIST_FAILED =
  "FETCH_UPLOADING_PENDING_DOC_LIST_FAILED"


export const UPLOAD_PENDING_DOCUMENT_ID = "UPLOAD_PENDING_DOCUMENT_ID"
export const UPLOAD_PENDING_DOCUMENT_ID_SUCCESS = "UPLOAD_PENDING_DOCUMENT_ID_SUCCESS"
export const UPLOAD_PENDING_DOCUMENT_ID_FAIL = "UPLOAD_PENDING_DOCUMENT_ID_FAIL"
export const GET_UPLOAD_PENDING_DOCUMENT_OPEN = "GET_CA_CERTIFICATE_FILE"
