export const APPROVE_TRANSACTION_REOPEN_START =
  "APPROVE_TRANSACTION_REOPEN_START"
export const APPROVE_TRANSACTION_REOPEN_SUCCESS =
  "APPROVE_TRANSACTION_REOPEN_SUCCESS"
export const APPROVE_TRANSACTION_REOPEN_FAILED =
  "APPROVE_TRANSACTION_REOPEN_FAILED"
