

export const CHANGE_FIRST_PASSWORD = "CHANGE_FIRST_PASSWORD"
export const CHANGE_FIRST_PASSWORD_SUCCESS = "CHANGE_FIRST_PASSWORD_SUCCESS"
export const CHANGE_FIRST_PASSWORD_FAIL = "CHANGE_FIRST_PASSWORD_FAIL"



export const CHANGE_ONE_TIME_PASSWORD = "CHANGE_ONE_TIME_PASSWORD"
export const CHANGE_ONE_TIME_PASSWORD_SUCCESS = "CHANGE_ONE_TIME_PASSWORD_SUCCESS"
export const CHANGE_ONE_TIME_PASSWORD_FAIL = "CHANGE_ONE_TIME_PASSWORD_FAIL"


