/* INVOICES */
export const GET_INVOICES = "GET_INVOICES"
export const GET_INVOICES_SUCCESS = "GET_INVOICES_SUCCESS"
export const GET_INVOICES_FAIL = "GET_INVOICES_FAIL"

export const GET_INVOICE_DETAIL = "GET_INVOICE_DETAIL"
export const GET_INVOICE_DETAIL_SUCCESS = "GET_INVOICE_DETAIL_SUCCESS"
export const GET_INVOICE_DETAIL_FAIL = "GET_INVOICE_DETAIL_FAIL"

export const ADD_INVOICE ="ADD_INVOICE"
export const ADD_INVOICE_SUCCESS ="ADD_INVOICE_SUCCESS"
export const ADD_INVOICE_FAIL  ="ADD_INVOICE_FAIL"

export const ADD_FILES ="ADD_FILES"
export const ADD_FILES_SUCCESS ="ADD_FILES_SUCCESS"
export const ADD_FILES_FAIL  ="ADD_FILES_FAIL"
