export const GET_EMPLOYEE = "GET_EMPLOYEE_LIST"
export const GET_EMPLOYEE_LIST_SUCCESS = "GET_EMPLOYEE_LIST_SUCCESS"
export const GET_EMPLOYEE_LIST_FAIL = "GET_EMPLOYEE_LIST_FAIL"

export const ADD_NEW_EMPLOYEE = "ADD_NEW_EMPLOYEE"
export const ADD_NEW_EMPLOYEE_SUCCESS = "ADD_NEW_EMPLOYEE_SUCCESS"
export const ADD_NEW_EMPLOYEE_FAIL = "ADD_NEW_EMPLOYEE_FAIL"
