export const FETCH_GST_DETAIL_START =
  "FETCH_GST_DETAIL_START"
export const FETCH_GST_DETAIL_SUCCESS =
  "FETCH_GST_DETAIL_SUCCESS"
export const FETCH_GST_DETAIL_FAILED =
  "FETCH_GST_DETAIL_FAILED"
