export const FETCH_APPROVE_REPORT_DEFAULTER_START =
  "FETCH_APPROVE_REPORT_DEFAULTER_START"
export const FETCH_APPROVE_REPORT_DEFAULTER_SUCCESS =
  "FETCH_APPROVE_REPORT_DEFAULTER_SUCCESS"
export const FETCH_APPROVE_REPORT_DEFAULTER_FAILED =
  "FETCH_APPROVE_REPORT_DEFAULTER_FAILED"
