export const FETCH_COMPANY_SEARCH_VIEW_DETAIL_START =
  "FETCH_COMPANY_SEARCH_VIEW_DETAIL_START"
export const FETCH_COMPANY_SEARCH_VIEW_DETAIL_SUCCESS =
  "FETCH_COMPANY_SEARCH_VIEW_DETAIL_SUCCESS"
export const FETCH_COMPANY_SEARCH_VIEW_DETAIL_FAILED =
  "FETCH_COMPANY_SEARCH_VIEW_DETAIL_FAILED"
