export const FETCH_REPORT_ME_DEFULTER_START =
  "FETCH_REPORT_ME_DEFULTER_START"
export const FETCH_REPORT_ME_DEFULTER_SUCCESS =
  "FETCH_REPORT_ME_DEFULTER_SUCCESS"
export const FETCH_REPORT_ME_DEFULTER_FAILED =
  "FETCH_REPORT_ME_DEFULTER_FAILED"
