export const FETCH_REPORT_DEFULTER_PREVIEW_START =
  "FETCH_REPORT_DEFULTER_PREVIEW_START"
export const FETCH_REPORT_DEFULTER_PREVIEW_SUCCESS =
  "FETCH_REPORT_DEFULTER_PREVIEW_SUCCESS"
export const FETCH_REPORT_DEFULTER_PREVIEW_FAILED =
  "FETCH_REPORT_DEFULTER_PREVIEW_FAILED"
