export const GET_ALL_SUBSCRIPTION_PACKAGE =
  "GET_ALL_SUBSCRIPTION_PACKAGE"
export const GET_ALL_SUBSCRIPTION_PACKAGE_SUCCESS =
  "GET_ALL_SUBSCRIPTION_PACKAGE_SUCCESS"
export const GET_ALL_SUBSCRIPTION_PACKAGE_FAILED =
  "GET_ALL_SUBSCRIPTION_PACKAGE_FAILED"


  export const ADD_SUBSCRIPTION_TO_USER =
  "ADD_SUBSCRIPTION_TO_USER"
export const ADD_SUBSCRIPTION_TO_USER_SUCCESS =
  "ADD_SUBSCRIPTION_TO_USER_SUCCESS"
export const ADD_SUBSCRIPTION_TO_USER_FAILED =
  "ADD_SUBSCRIPTION_TO_USER_FAILED"



